server:
  port: 20661
  servlet:
    context-path: /generatetemplateprovider

spring:
  application:
    name: generatetemplateprovider
  profiles: dev

  activemq:
    broker-url: tcp://10.6.90.83:61616
  jms:
    template:
      default-destination: countrylicense

  data:
    mongodb:
        uri: mongodb://license:linewell_license123@10.6.90.6:27017,10.6.90.3:27017/license?authSource=admin&replicaSet=zzmongo&authMechanism=SCRAM-SHA-1&minPoolSize=3&maxPoolSize=10&w=1&readPreference=secondaryPreferred&connectTimeoutMS=300000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&autoReconnect=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

logging:
  pattern:
    console: time %d{yyyy/MM/dd-HH:mm:sss} [%thread] %-5level %logger- %msg%n
    file: time %d{yyyy/MM/dd} [%thread] %-5level %logger- %msg%n
  path: logs

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eurekaserver/eureka
info:
  author: corrin
  version: 0.0.1
  date: 2019-09-07