server:
  port: 20663
  servlet:
    context-path: /gridfsprovider

spring:
  application:
    name: gridfsprovider
  profiles: dev

  data:
    mongodb:
        uri: mongodb://license:linewell_license123@10.6.90.6:27017,10.6.90.3:27017/LicenseFilesDB?authSource=admin&replicaSet=zzmongo&authMechanism=SCRAM-SHA-1&minPoolSize=3&maxPoolSize=10&w=1&readPreference=secondaryPreferred&connectTimeoutMS=300000

logging:
  pattern:
    console: time %d{yyyy/MM/dd-HH:mm:sss} [%thread] %-5level %logger- %msg%n
    file: time %d{yyyy/MM/dd} [%thread] %-5level %logger- %msg%n
  path: logs

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eurekaserver/eureka
info:
  author: corrin
  version: 0.0.1
  date: 2019-09-07